### ISSUE TITLE
Login incorrectly crashes app

### ISSUE THREAD

**Issue by Huyzy** [leachad/buuteeq-ponyhax#1]
This was actually found by @youngbw , so applause to him to finding it :)

Try to login incorrectly.
It will crash with the following stack trace:
04-12 22:35:04.037  28029-28029/uw.buuteeq_ponyhax.phase_one E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: uw.buuteeq_ponyhax.phase_one, PID: 28029
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.matches(java.lang.String)' on a null object reference
            at uw.buuteeq_ponyhax.app.LoginActivity.checkUserCredentials(LoginActivity.java:114)
            at uw.buuteeq_ponyhax.app.LoginActivity.access$100(LoginActivity.java:12)
            at uw.buuteeq_ponyhax.app.LoginActivity$LoginListener.onClick(LoginActivity.java:163)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Huyzy** [comment]
@leachad probably knows more about this!

**Comment by leachad** [comment]
I was trying to debug that issue last night. I think it may have something
to do with multiple instances of the DBHelper within the LoginActivity.
Continuing work on it this morning. I'll let you guys know I figure out.

On Sun, Apr 12, 2015 at 10:42 PM, Huyzy <notifications@github.com> wrote:

> @leachad <https://github.com/leachad> probably knows more about this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leachad/buuteeq-ponyhax/issues/1#issuecomment-92220304>
> .
>



-- 

*Best,*

*Andy*

*--------------------------------Andrew Leach*
Professional Technician
Tacoma Public Schools ELL
253-571-1110
aleach@tacoma.k12.wa.us

**Comment by Huyzy** [comment]
Ah okay, I'll get this fixed during class.
